sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in kube.json.enc -out kube.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file kube.json
  - gcloud config set project kube-268017
  - gcloud config set compute/zone us-east4-b
  - gcloud container clusters get-credentials kube-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sunitha-premakumaran/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run sunitha-premakumaran/react-test npm test -- --coverage